version: '3.8'

services:

  # Service nommé apache
  apache:
    image: httpd:latest
    container_name: my-apache-app
    ports:
    - '80:80'
    volumes:
    - ./src:/usr/local/apache2/htdocs
    working_dir: /usr/local/apache2/htdocs/

  # PHP Service
  php:
    image: php:8.1-fpm
    container_name: phpPV
    working_dir: /var/www/
    volumes:
      - ./src:/var/www/
      - ./chemin/vers/votre/php.ini:/usr/local/etc/php/conf.d/php.ini
    #depends_on:
    #  mysql:
    #    condition: service_healthy

  # MySQL Service
  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysqlPV
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306

  # PhpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    container_name: phpmyadminPV
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    #depends_on:
    #    mysql:
    #        condition: service_healthy

volumes:
  mysqldata:
    driver: local